const options = [
  'Offa',
  'Egbert ',
  'Aethelwulf',
  'Aethelbald',
  'Aethelbert',
  'Aethelred I',
  'Alfred the Great',
  'Edward the Elder',
  'Athelstan',
  'Edmund',
  'Edred',
  'Edwy',
  'Edgar',
  'Edward the Martyr',
  'Ethelred II the Unready',
  'Edmund lronside',
  'Cnut',
  'Harold I Harefoot',
  'Harthacanut',
  'Edward the Confessor ',
  'Harold II',
  'William I',
  'William II',
  'Henry I',
  'Stephen',
  'Henry II ',
  'Richard I',
  'John',
  'Henry III',
  'Edward I',
  'Edward II',
  'Edward III',
  'Richard II',
  'Henry IV',
  'Henry V',
  'Henry VI ',
  'Edward IV',
  'Edward V ',
  'Richard III',
  'Henry VII',
  'Henry VIII',
  'Edward VI',
  'Mary I',
  'Elizabeth I',
  'James I',
  'Charles I ',
  'Oliver Cromwell',
  'Richard Cromwell',
  'Charles II',
  'James II',
  'William III',
  'Anne',
  'George I',
  'George II',
  'George III',
  'George IV',
  'William IV',
  'Victoria',
  'Edward VII',
  'George V',
  'Edward VIII',
  'George VI',
  'Elizabeth II',
  'Charles III'
]

export default function () {
  const r = Math.floor(Math.random() * options.length)
  return options[r]
}
