const options = [
  'Abenaki mythology',
  'Advaita Vedanta',
  'Ahl al-Hadith',
  'Ahmadiyya Muslim Community',
  'Akamba mythology (East Kenya)',
  'Akan mythology',
  'Akhbari',
  'Al-Fatiha Foundation',
  'Alawites',
  'Alevi',
  'Alevism / Bektashi Order',
  'Alevism',
  'Alexandrian Wicca',
  'Algard Wicca',
  'Alternative Judaism',
  'American Society of Muslims',
  'Anabaptists',
  'Ananda Marga',
  'Ancient Mystical Order Rosae Crucis',
  'Anglicanism',
  'Anglo-Saxon religion',
  'Anishinaabe',
  'Anito',
  'Anthroposophy',
  'Arabian mythology (pre-Islamic)',
  'Archeosophical Society',
  'Arianism',
  'Armenian Neopaganism',
  'Armenian Orthodox',
  'Arya Samaj',
  'Asatru',
  "Ash'ari",
  'Ashanti mythology (Ghana)',
  'Ashtanga Yoga',
  'Azali',
  'Azali',
  'Azraqi',
  'Aztec mythology',
  'A∴A∴',
  'Bábism',
  'Babylonian and Assyrian religion',
  'Babylonian mythology',
  'Bagnolians',
  "Bahá'í Faith",
  "Bahá'ís Under the Provisions of the Covenant",
  'Baltic Neopaganism',
  'Bambuti (Pygmy) mythology (Congo)',
  'Bangladeshi Mahasthabir Nikaya',
  'Bangladeshi Sangharaj Nikaya',
  'Baptists',
  'Bardaisan',
  'Barelvi',
  'Barom Kagyu',
  'Basilideans',
  'Batuque',
  'Behafaridians',
  'Behmenism',
  'Bektashi Order',
  'Bektashi Order',
  'Benzhuism (indigenous religion of the Bai people)',
  'Bhakti Yoga',
  'Bimoism (indigenous religion of the Yi people)',
  'Bispanthi',
  'Blackfoot mythology',
  'Blue Star Wicca',
  'Bon (indigenous religion of Tibet)',
  'Brahmo Samaj',
  'Brythonic mythology',
  'Builders of the Adytum',
  'Bulgarian Orthodox',
  'Burmese Dwara Nikaya',
  'Burmese Shwegyin Nikaya',
  'Burmese Thudhamma Nikaya',
  'Bushongo mythology (Congo)',
  'Calvinism',
  'Canaanite mythology',
  'Canaanite religion',
  'Canadian Muslim Union',
  'Candomblé',
  'Cao Đài',
  'Celtic Neopaganism',
  'Central Valley Wicca',
  'Chaldean mythology',
  'Chan Buddhism',
  'Cheondoism',
  'Cheontae',
  'Cherokee mythology',
  'Chickasaw mythology',
  'Chinese folk religion',
  'Chinese mythology',
  'Chishti Order',
  'Choctaw mythology',
  'Christadelphians',
  'Christian Gnosticism',
  'Christian Identity',
  'Christian Kabbalah',
  'Christian Science',
  'Christian Science',
  'Christian Universalism',
  'Chthonioi Alexandrian Wicca',
  'Church Universal and Triumphant',
  'Church of World Messianity',
  'Congregational churches',
  'Conservadox Judaism',
  'Conservative Judaism',
  'Continental Germanic religion',
  'Coptic Orthodox',
  'Covenant of the Goddess',
  'Creek mythology',
  'Crow mythology',
  'Cult of the Supreme Being',
  'Daejongism',
  'Daesun Jinrihoe',
  'Dagpo Kagyu',
  'Dahomey (Fon) mythology',
  'Dahomey mythology',
  'Dances of Universal Peace',
  'Daśabhūmikā (absorbed into Huayan)',
  'Deism',
  'Deobandi',
  'Dhammakaya Movement',
  'Diamond Way Buddhism',
  'Digambar Terapanth',
  'Dinka mythology (Sudan)',
  'Discordianism',
  'Divine Science',
  'Dragon Gate Taoism',
  'Drukpa Lineage',
  'Dudeism',
  'Dvaita Vedanta',
  'East Asian Mādhyamaka (Three Treatise school)',
  'East Asian Yogācāra',
  'Ebionites',
  'Ebionites',
  'Ecclesia Gnostica Catholica (the ecclesiastical arm of O.T.O.)',
  'Ecclesia Gnostica',
  'Eckankar',
  'Eclectic Wicca',
  'Efik mythology (Nigeria, Cameroon)',
  'Elcesaites',
  'Eleusinian Mysteries',
  'Enochian magic',
  'Eskimo religion',
  'Essenes',
  'Estonian mythology',
  'Estonian polytheism',
  'Ethical Culture',
  'Ethiopian Orthodox',
  'European Islam',
  'Faism (Redhead Taoism)',
  'Falun Gong',
  'Finnish Neopaganism',
  'Finnish mythology and Finnish paganism',
  'Finnish polytheism',
  'Five-Percent Nation',
  'Fourth Way',
  'Frankism',
  'Fraternitas Saturni',
  'Fraternity of the Inner Light',
  'Fuke-shū',
  'Gabâ',
  'Gaelic mythology',
  'Gardnerian Wicca',
  'Gasin faith',
  'Gaudiya Vaishnavism',
  'Gedimu',
  'Germanic Neopaganism',
  'Ghair Muqallidism',
  'Ghost Dance',
  'Giin line',
  'Goddess movement',
  'Goetic magic',
  'Greek Orthodox',
  'Guarani mythology',
  'Haida mythology',
  'Haitian mythology',
  'Hanafi',
  'Hanbali',
  'Happy Science',
  'Haredi Judaism',
  'Haruriyyah',
  'Hasidic Judaism',
  'Hatha yoga',
  'Hellenismos',
  'Hermetic Order of the Golden Dawn',
  'Hermeticism',
  'Hinduism in Indonesia',
  'Historical Vedic religion',
  'Ho-Chunk mythology (aka: Winnebago)',
  'Hòa Hảo',
  'Hopi mythology',
  'Huayan school (Avataṃsaka)',
  'Humanism',
  'Humanistic Judaism',
  'Hungarian folk religion',
  'Hungarian polytheism',
  'Hwaeom',
  'Ibadi',
  'Igbo mythology (Nigeria, Cameroon)',
  'Iglesia ni Cristo',
  'Illuminates of Thanateros',
  'Inca mythology',
  'Indian Shaker Church',
  'Integral Yoga',
  'International Society for Krishna Consciousness',
  'Inuit mythology',
  'Iranian mythology',
  'Iroquois mythology',
  "Isma'ilism",
  'Isoko mythology (Nigeria)',
  'Ittifaq al-Muslimin',
  "Ja'fari jurisprudence",
  'Jadid',
  'Jahriyya',
  'Jakuen line',
  'Jamaat al Muslimeen',
  'Japanese mythology',
  "Jehovah's Witnesses",
  'Jesuism',
  'Jesusism',
  'Jeung San Do',
  'Jewish Renewal',
  'Jewish Science',
  'Jnana yoga',
  'John Frum',
  'Jonang',
  'Jonang',
  'Juche',
  'Jōdo Shinshū',
  'Jōdo-shū',
  'Kabir panth',
  'Kanji Panth',
  'Karma Kagyu',
  'Karma yoga',
  'Keetoowah Nighthawk Society',
  'Kegon',
  'Keizan line',
  'Kemetism',
  'Khalsa',
  'Khoisan religion',
  'Khufiyya',
  "Khurramites (syncretism with Shi'a Islam)",
  'Konkokyo',
  'Konkokyo',
  'Korean shamanism',
  'Korean shamanism',
  'Koshintō',
  'Koshintō',
  'Kuksu',
  'Kulam',
  'Kumina',
  'Kundalini yoga',
  'Kwakiutl mythology',
  'LaVeyan Satanism',
  'Lahore Ahmadiyya Movement for the Propagation of Islam',
  'Lakota mythology',
  'Latter Day Saint movement',
  'Leni Lenape mythology',
  'Liberal Judaism',
  'Liberal movements within Islam',
  'Lingbao School ("School of the Numinous Treasure")',
  'Longhouse religion',
  'Lotuko mythology (Sudan)',
  'Lozi mythology (Zambia)',
  'Lugbara mythology (Congo)',
  'Lutheranism',
  'Macumba',
  'Mahdaviav',
  'Main articles: Christian mysticism and Esoteric Christianity',
  'Maliki',
  'Mami Wata',
  'Manchu Shamanism',
  'Mandaean Nasaraean Sabeans',
  'Mandaeism',
  'Mandaeism',
  'Mandaeism',
  'Manichaeism',
  'Manichaeism',
  'Mapuche mythology',
  'Marcionism',
  'Marla faith',
  'Martinism',
  'Masai mythology (Kenya, Tanzania)',
  'Masorti',
  'Matua Mahasangha',
  'Maturidi',
  'Maya mythology',
  'Mazdakism',
  'Members Church of God International',
  'Messiah Foundation International',
  'Messianic Judaism',
  'Methodism',
  'Mevlevi Order',
  'Midewiwin',
  'Millerites',
  'Mithraism',
  'Mithraism',
  'Miwok',
  'Moai',
  'Modekngei',
  'Modern Orthodox Judaism',
  'Mohism',
  'Moorish Orthodox Church of America',
  'Moorish Orthodox Church of America',
  'Moorish Science Temple of America',
  'Moravians',
  "Mu'tazila",
  'Mujaddidiyah',
  'Mun (Lepcha)',
  "Murji'ah",
  'Murtipujaka (Deravasi)',
  'Muslim Canadian Congress',
  'Mustaali / Dawoodi Bohra',
  'Muwahhidism',
  'Māori religion',
  'Namdhari ("Kuka Sikhs")',
  'Naqshbandi',
  'Nation of Islam',
  'Native American Church',
  'Naturalistic Pantheism (e.g. World Pantheist Movement)',
  'Nauruan indigenous religion',
  'Navajo mythology',
  'Nazarenes',
  'Neo-Confucianism',
  'Neopythagoreanism',
  'New Confucianism',
  'New Kadampa Tradition',
  'New Orleans Voodoo',
  "Ni'matullāhī",
  'Nichiren Shū',
  'Nichiren Shōshū',
  'Nihang',
  'Nipponzan-Myōhōji-Daisanga',
  'Nizari',
  'Nonconformism',
  'Nontrinitarianism',
  'Nootka mythology',
  'Norse religion',
  'Nuwaubian Nation',
  'Obeah',
  'Odinism',
  'Ohlone mythology',
  'Olmec mythology',
  'Oomoto',
  'Oomoto',
  'Open-source religion',
  'Ordo Aurum Solis',
  'Ordo Templi Orientis',
  'Orphism',
  "Orthodox Bahá'í Faith",
  'Orthodox Judaism',
  'Our Lady of Endor Coven (or Ophite Cultus Satanas)',
  'Oyotunji',
  'PL Kyodan',
  'Palo',
  'Panth of Kanji Swami',
  'Pawnee mythology',
  'Pentecostalism',
  'Pharisees (ancestor of Rabbinic Judaism)',
  'Pietism',
  'Plurationalism',
  'Pomo mythology',
  'Prasaṅgika',
  'Presbyterianism',
  'Prince Philip Movement',
  'Progressive British Muslims',
  'Progressive Judaism',
  'Progressive Muslim Union',
  'Qadiriyya',
  'Quakerism',
  'Quanzhen School ("Way of the Fulfilled Virtue")',
  'Quimbanda',
  'Quranism',
  'Raja yoga',
  'Ramakrishna Mission',
  'Rastafarianism',
  'Ravidassia religion',
  'Ravidassia religion',
  'Reconstructionist Judaism',
  'Reform Judaism',
  'Reformed Druids of North America',
  'Religious Science',
  'Riaz Ahmed Gohar Shahi',
  'Rinzai school',
  'Roman Neopaganism',
  'Romanian Orthodox',
  'Romuva',
  'Rosicrucian Fellowship',
  'Rosicrucian',
  'Russian Orthodox',
  'Sabbateans',
  'Sabians of Harran',
  'Sabians',
  'Sadducees (possible ancestor of Karaite Judaism)',
  'Sahaja Yoga',
  'Sahajdhari',
  'Salafi movement',
  'Salish mythology',
  'Sami religion (including the Noaidi)',
  'Sant Mat',
  'Santería (Lukumi)',
  'Satsang of Thakur Anukulchandra',
  'Satya Dharma',
  'Second Temple Judaism',
  'Sects that believed Jesus was a prophet',
  'Seicho-No-Ie',
  'Seicho-no-Ie',
  'Seicho-no-Ie',
  "Selk'nam religion",
  'Semitic Neopaganism',
  'Seneca mythology',
  'Serbian Orthodox',
  'Servants of the Light',
  'Sethianism',
  'Seventh-day Adventist Church',
  "Shafi'i",
  'Shakers',
  'Shambhala Buddhism',
  'Shangpa Kagyu',
  'Shangqing School ("School of the Highest Clarity")',
  'Share International',
  'Shaykhism',
  'Shinmeiaishinkai',
  'Shugendō',
  'Siberian Shamanism',
  'Sicarii',
  'Siddha Yoga',
  'Slavic Neopaganism',
  'Soka Gakkai',
  'Some forms of freethought (e.g. North Texas Church of Freethought)',
  'Southeastern Ceremonial Complex',
  'Spiritism (Spiritualism)',
  'Spiritual Baptists',
  'Sri Lankan Amarapura Nikaya',
  'Sri Lankan Ramañña Nikaya',
  'Sri Lankan Siam Nikaya',
  'Sthānakavāsī',
  'Subud',
  'Sufi Order International',
  'Sufism Reoriented',
  'Sufri',
  'Suhrawardiyya',
  'Sumerian mythology',
  'Sun Dance',
  'Surat Shabd Yoga',
  'Suwunism',
  'Svatantrika',
  'Svetambar Terapanth',
  'Swedenborgianism',
  'Syriac Orthodox',
  'Sōtō',
  'Taaraism',
  'Taipingjing-based movements',
  'Tangata manu',
  'Tantra',
  'Tantric Yoga',
  'Tariqa',
  'Tendai',
  'Tengrism',
  'Tenrikyo',
  'Tenrikyo',
  'Thai Dhammayuttika Nikaya',
  'Thai Forest Tradition',
  'Thai Maha Nikaya',
  'The Aquarian Church',
  'The Church of Jesus Christ of Latter-day Saints',
  'The New Message from God',
  'The Open Source Order of the Golden Dawn',
  'The Osho or Rajneesh movement',
  'Thee Temple ov Psychick Youth',
  'Theistic Satanism',
  'Tijaniyyah',
  'Tolu-e-Islam',
  'Tradition of Ajahn Chah',
  'Triratna Buddhist Community',
  'True Buddha School',
  'Tsimshian mythology',
  'Tumbuka mythology (Malawi)',
  'Twelver',
  'Typhonian Order',
  'Ua Dab (indigenous religion of the Hmong people)',
  'Umbanda',
  'Unification Church',
  'Union for Traditional Judaism',
  'Unitarianism',
  'United Nation of Islam',
  'United Submitters International',
  'Unity Church',
  'Universal Church of the Kingdom of God',
  'Universal Life Church',
  'Universal Sufism',
  'Urarina',
  'Usuli',
  'Ute mythology',
  'Vaastu Shastra',
  'Vailala Madness',
  'Valentinianism',
  'Vietnamese folk religion',
  'Vipassana tradition of Mahasi Sayadaw and disciples',
  'Vishishtadvaita',
  'Vodou',
  'Wahhabism',
  'Waldensians',
  'Way of the Celestial Masters',
  'Way of the Five Pecks of Rice',
  'Won Buddhism',
  'Wotanism',
  'Wuliupai ("School of Wu-Liu")',
  'Wyandot religion',
  'Xiantiandao',
  'Xidaotang',
  'Xuanxue (Neo-Taoism)',
  'Yao Taoism (Meishanism)',
  'Yarsani',
  'Yarsanism',
  'Yazidi',
  'Yiguandao (I Kuan-Tao)',
  'Yiguandao',
  'Yihewani',
  'Yoism',
  'Yoruba mythology (Nigeria, Benin)',
  'Yoshida Shintō',
  'Zaidiyyah',
  'Zalmoxianism',
  'Zealots (Judea)s',
  'Zenarchy (Kerry Wendell Thornley)',
  'Zenrinkyo',
  'Zhengyi Dao ("Way of the Right Oneness")',
  'Zulu mythology (South Africa)',
  'Zuni mythology',
  'Zurvanism',
  'Ōbaku',
  'Đạo Bửu Sơn Kỳ Hương',
  'Đạo Dừa',
  'Đạo Mẫu'
]

module.exports = () => {
  const r = Math.floor(Math.random() * options.length)
  return options[r]
}
